server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: RATING-SERVICE
                fallbackuri: forward:/ratingServiceFallBack
        - id: REVIEW-SERVICE
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**
          filters:
            - name: CircuitBreaker
              args:
                name: REVIEW-SERVICE
                fallbackuri: forward:/reviewServiceFallBack
        - id: DETAIL-SERVICE
          uri: lb://DETAIL-SERVICE
          predicates:
            - Path=/details/**
          filters:
            - name: CircuitBreaker
              args:
                name: DETAIL-SERVICE
                fallbackuri: forward:/detailServiceFallBack
        - id: PAGE-SERVICE
          uri: lb://PAGE-SERVICE
          predicates:
            - Path=/pages/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAGE-SERVICE
                fallbackuri: forward:/pageServiceFallBack

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.rtb.svc.cluster.local:8761/eureka

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
